//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelWithMe.TravelPlaces {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TravelPlaces.IPopularPlaceFinder")]
    public interface IPopularPlaceFinder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopularPlaceFinder/getNearByPopularPlaces", ReplyAction="http://tempuri.org/IPopularPlaceFinder/getNearByPopularPlacesResponse")]
        string[] getNearByPopularPlaces(string cityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopularPlaceFinder/getNearByPopularPlaces", ReplyAction="http://tempuri.org/IPopularPlaceFinder/getNearByPopularPlacesResponse")]
        System.Threading.Tasks.Task<string[]> getNearByPopularPlacesAsync(string cityName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPopularPlaceFinderChannel : TravelWithMe.TravelPlaces.IPopularPlaceFinder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PopularPlaceFinderClient : System.ServiceModel.ClientBase<TravelWithMe.TravelPlaces.IPopularPlaceFinder>, TravelWithMe.TravelPlaces.IPopularPlaceFinder {
        
        public PopularPlaceFinderClient() {
        }
        
        public PopularPlaceFinderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PopularPlaceFinderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PopularPlaceFinderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PopularPlaceFinderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getNearByPopularPlaces(string cityName) {
            return base.Channel.getNearByPopularPlaces(cityName);
        }
        
        public System.Threading.Tasks.Task<string[]> getNearByPopularPlacesAsync(string cityName) {
            return base.Channel.getNearByPopularPlacesAsync(cityName);
        }
    }
}
