//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelWithMe.NewsFocusService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsFocusService.INewsFocus")]
    public interface INewsFocus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsFocus/DoWork", ReplyAction="http://tempuri.org/INewsFocus/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsFocus/DoWork", ReplyAction="http://tempuri.org/INewsFocus/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsFocus/getNews", ReplyAction="http://tempuri.org/INewsFocus/getNewsResponse")]
        string[] getNews(string[] topics);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsFocus/getNews", ReplyAction="http://tempuri.org/INewsFocus/getNewsResponse")]
        System.Threading.Tasks.Task<string[]> getNewsAsync(string[] topics);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsFocusChannel : TravelWithMe.NewsFocusService.INewsFocus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsFocusClient : System.ServiceModel.ClientBase<TravelWithMe.NewsFocusService.INewsFocus>, TravelWithMe.NewsFocusService.INewsFocus {
        
        public NewsFocusClient() {
        }
        
        public NewsFocusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsFocusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsFocusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsFocusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string[] getNews(string[] topics) {
            return base.Channel.getNews(topics);
        }
        
        public System.Threading.Tasks.Task<string[]> getNewsAsync(string[] topics) {
            return base.Channel.getNewsAsync(topics);
        }
    }
}
