//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelWithMe.CrimeData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrimeData.ICrimeData")]
    public interface ICrimeData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrimeData/getCrimeData", ReplyAction="http://tempuri.org/ICrimeData/getCrimeDataResponse")]
        int getCrimeData(int zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrimeData/getCrimeData", ReplyAction="http://tempuri.org/ICrimeData/getCrimeDataResponse")]
        System.Threading.Tasks.Task<int> getCrimeDataAsync(int zipcode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrimeDataChannel : TravelWithMe.CrimeData.ICrimeData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrimeDataClient : System.ServiceModel.ClientBase<TravelWithMe.CrimeData.ICrimeData>, TravelWithMe.CrimeData.ICrimeData {
        
        public CrimeDataClient() {
        }
        
        public CrimeDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrimeDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrimeDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrimeDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int getCrimeData(int zipcode) {
            return base.Channel.getCrimeData(zipcode);
        }
        
        public System.Threading.Tasks.Task<int> getCrimeDataAsync(int zipcode) {
            return base.Channel.getCrimeDataAsync(zipcode);
        }
    }
}
