//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelWithMe.CarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarService.ICarRental")]
    public interface ICarRental {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRental/DoWork", ReplyAction="http://tempuri.org/ICarRental/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRental/DoWork", ReplyAction="http://tempuri.org/ICarRental/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRental/carFinder", ReplyAction="http://tempuri.org/ICarRental/carFinderResponse")]
        string[] carFinder(string destination, string startDate, string endDate, string pickTime, string dropOffTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRental/carFinder", ReplyAction="http://tempuri.org/ICarRental/carFinderResponse")]
        System.Threading.Tasks.Task<string[]> carFinderAsync(string destination, string startDate, string endDate, string pickTime, string dropOffTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarRentalChannel : TravelWithMe.CarService.ICarRental, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarRentalClient : System.ServiceModel.ClientBase<TravelWithMe.CarService.ICarRental>, TravelWithMe.CarService.ICarRental {
        
        public CarRentalClient() {
        }
        
        public CarRentalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarRentalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarRentalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarRentalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string[] carFinder(string destination, string startDate, string endDate, string pickTime, string dropOffTime) {
            return base.Channel.carFinder(destination, startDate, endDate, pickTime, dropOffTime);
        }
        
        public System.Threading.Tasks.Task<string[]> carFinderAsync(string destination, string startDate, string endDate, string pickTime, string dropOffTime) {
            return base.Channel.carFinderAsync(destination, startDate, endDate, pickTime, dropOffTime);
        }
    }
}
